permalink: pretty
collections:
  people:
    output: true
    permalink: /people/:path/
  classes:
    output: true
    permalink: /classes/:path/
  faqs:
    output: true
    permalink: /faq/:path/
defaults:
  -
    scope:
      path: ""
      type: "classes" # a collection in your site, in plural form
    values:
      layout: "class"
